# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0002_auto_20190701_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='users_auths',
            name='login_status',
            field=models.BooleanField(default=0, verbose_name='登录状态'),
        ),
    ]
