# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_from',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_data', models.DateField(verbose_name='订餐日期')),
                ('check_time', models.CharField(max_length=100, verbose_name='订单时段')),
                ('check_person', models.CharField(max_length=50, verbose_name='人数')),
                ('check_phone', models.CharField(max_length=50, verbose_name='电话号码')),
                ('check_table', models.CharField(max_length=50, verbose_name='桌号')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserProfile')),
            ],
            options={
                'db_table': 'UOrder_from',
            },
        ),
    ]
