# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_from',
            name='check_time',
            field=models.CharField(max_length=100, verbose_name='订单时段'),
        ),
    ]
