# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-06-30 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
        ('single', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcount', models.IntegerField(verbose_name='菜品数量')),
                ('lmoney', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='菜品金额')),
            ],
            options={
                'db_table': 'Orderlist',
            },
        ),
        migrations.CreateModel(
            name='Ordertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='订单日期')),
                ('orderid', models.CharField(max_length=30, verbose_name='订单编号')),
                ('table', models.CharField(max_length=30, verbose_name='桌号')),
                ('allmoney', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='订单金额')),
                ('otype', models.IntegerField(verbose_name='订单状态')),
                ('odish', models.IntegerField(verbose_name='配餐状态')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserProfile')),
            ],
            options={
                'db_table': 'Ordertable',
            },
        ),
        migrations.AddField(
            model_name='orderlist',
            name='check_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Ordertable'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='cid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='single.Menu'),
        ),
    ]
