# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userinfo', '0001_initial'),
        ('single', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lcount', models.IntegerField(verbose_name='菜品数量')),
                ('lmoney', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='菜品金额')),
            ],
            options={
                'verbose_name_plural': '订单明细表',
                'db_table': 'Orderlist',
            },
        ),
        migrations.CreateModel(
            name='Ordertable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='订单日期')),
                ('orderid', models.CharField(max_length=30, verbose_name='订单编号')),
                ('table', models.CharField(max_length=30, verbose_name='桌号')),
                ('allmoney', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='订单金额')),
                ('otype', models.IntegerField(verbose_name='订单状态')),
                ('odish', models.IntegerField(verbose_name='配餐状态')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserProfile')),
            ],
            options={
                'verbose_name_plural': '订单表',
                'db_table': 'Ordertable',
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(default='', max_length=50, verbose_name='菜名')),
                ('cprice', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='价格')),
                ('pic', models.ImageField(upload_to='dishes/', verbose_name='图片')),
                ('number', models.CharField(default='1', max_length=50, verbose_name='数量')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userinfo.UserProfile')),
            ],
            options={
                'verbose_name_plural': '购物车明细表',
                'db_table': 'Shoppingcart',
            },
        ),
        migrations.CreateModel(
            name='Takeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('addr', models.CharField(max_length=500, verbose_name='地址 ')),
                ('number', models.CharField(max_length=20, verbose_name='门牌号')),
                ('oid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.Ordertable')),
            ],
            options={
                'verbose_name_plural': '外卖表',
                'db_table': 'Takeout',
            },
        ),
        migrations.AddField(
            model_name='orderlist',
            name='check_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Ordertable'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='cid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='single.Menu'),
        ),
    ]
