# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 11:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Takeout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(max_length=50, verbose_name='手机号')),
                ('addr', models.CharField(max_length=500, verbose_name='地址 ')),
                ('number', models.CharField(max_length=20, verbose_name='门牌号')),
                ('oid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='checkout.Ordertable')),
            ],
            options={
                'db_table': 'Takeout',
            },
        ),
    ]
