# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-09 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='订单日期'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='odish',
            field=models.IntegerField(default='0', verbose_name='配餐状态'),
        ),
        migrations.AlterField(
            model_name='ordertable',
            name='otype',
            field=models.IntegerField(default='0', verbose_name='订单状态'),
        ),
    ]
