# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-10 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20190709_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='cid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='single.Menu'),
        ),
    ]
