# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-12 20:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20190711_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='odish',
            field=models.IntegerField(default='1', verbose_name='配餐状态'),
        ),
    ]
