# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-08 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctype', models.CharField(default='', max_length=50, verbose_name='类型')),
                ('cname', models.CharField(default='', max_length=50, verbose_name='菜名')),
                ('cprice', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='价格')),
                ('cmarket_price', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='会员价')),
                ('pic', models.ImageField(upload_to='dishes/', verbose_name='图片')),
            ],
            options={
                'verbose_name_plural': '菜品表',
                'db_table': 'Menu',
            },
        ),
        migrations.CreateModel(
            name='MenuInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduct', models.CharField(default='', max_length=5000, verbose_name='菜品简介')),
                ('value', models.CharField(default='', max_length=5000, verbose_name='营养价值')),
                ('infor', models.CharField(default='', max_length=5000, verbose_name='产地信息')),
                ('cid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='single.Menu')),
            ],
            options={
                'verbose_name_plural': '菜品明细表',
                'db_table': 'MenuInfo',
            },
        ),
    ]
